name: Demo Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 25f1000766@ds.study.iitm.ac.in
        run: echo "Hello, world!"
